language: cpp
solution: KinectToVR.sln
os: windows

env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"

install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
  - choco install dotnetcore-sdk
  - dotnet restore

script:
 - export PATH=$MSBUILD_PATH:$PATH
 - git clone https://github.com/USCiLab/cereal external/cereal
 - git clone https://github.com/ValveSoftware/openvr external/openvr
 - MSBuild.exe -p:Configuration=Release -p:Platform=x64 KinectToVR.sln