language: cpp
solution: KinectToVR.sln
os: windows

env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"

install:
  - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.ATL --add Microsoft.VisualStudio.Component.VC.ATLMFC --add Microsoft.VisualStudio.Component.Windows10SDK.18362"
  - choco install dotnetcore-sdk
  - dotnet restore

script:
 - export PATH=$MSBUILD_PATH:$PATH
 - git clone https://github.com/USCiLab/cereal external/cereal
 - git clone https://github.com/ValveSoftware/openvr external/openvr
 - wget "https://www.dropbox.com/s/9qledlbsehcywri/boost_1_74_0.7z?dl=1" -O ./external/boost_1_74_0.7z
 - wget "https://drive.google.com/uc?export=download&id=14TBSyxF9AfTd5n05guthFRfpxeh0nxLX" -O ./external/kinectlib.7z
 - 7z x ./external/boost_1_74_0.7z -oexternal
 - 7z x ./external/kinectlib.7z -oexternal
 - MSBuild.exe -p:Configuration=Release -p:Platform=x64 KinectToVR.sln -t:KinectToVR
