name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      id: checkout_code

    - name: Load Kinect SDK 1.8
      uses: actions/cache@v2
      with:
        path: KinectSDK-v1.8
        key: KinectSDK-v1.8-Setup

    - name: Load Kinect SDK 2.0
      uses: actions/cache@v2
      with:
        path: KinectSDK-v2.0
        key: KinectSDK-v2.0_1409-Setup

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild
      
    - name: Add MSYS64 bin to PATH
      run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Setup OpenVR
      run: git clone https://github.com/ValveSoftware/openvr external/openvr

    - name: Install Kinect SDK18
      shell: powershell
      run: |
        Set-Location ${{ github.workspace }}

        # Unpack the SDK if it hasn't been restored from cache
        if (!(Test-Path -PathType Container KinectSDK-v1.8)) {
            New-Item -ItemType directory KinectSDK-v1.8 | Out-Null
            wget "https://download.microsoft.com/download/E/1/D/E1DEC243-0389-4A23-87BF-F47DE869FC1A/KinectSDK-v1.8-Setup.exe" -OutFile KinectSDK-v1.8-Setup.exe
            & "C:\Program Files (x86)\WiX Toolset v3.11\bin\dark.exe" KinectSDK-v1.8-Setup.exe -x KinectSDK-v1.8
        
            Start-Process msiexec -ArgumentList "/a ${{ github.workspace }}\KinectSDK-v1.8\AttachedContainer\KinectSDK-v1.8-x64.msi /qn TARGETDIR=${{ github.workspace }}\KinectSDK-v1.8\AttachedContainer\SDK18" -Wait -NoNewWindow
        }

    - name: Install Kinect SDK20
      shell: powershell
      run: |
        Set-Location ${{ github.workspace }}

        # Unpack the SDK if it hasn't been restored from cache
        if (!(Test-Path -PathType Container KinectSDK-v2.0)) {
            New-Item -ItemType directory KinectSDK-v2.0 | Out-Null
            wget "https://download.microsoft.com/download/F/2/D/F2D1012E-3BC6-49C5-B8B3-5ACFF58AF7B8/KinectSDK-v2.0_1409-Setup.exe" -OutFile KinectSDK-v2.0_1409-Setup.exe
            & "C:\Program Files (x86)\WiX Toolset v3.11\bin\dark.exe" KinectSDK-v2.0_1409-Setup.exe -x KinectSDK-v2.0
            
            Start-Process msiexec -ArgumentList "/a ${{ github.workspace }}\KinectSDK-v2.0\AttachedContainer\KinectSDK-v2.0_1409-x64.msi /qn TARGETDIR=${{ github.workspace }}\KinectSDK-v2.0\AttachedContainer\SDK20" -Wait -NoNewWindow
        }

    - name: NuGet Restore KinectToVR
      run: nuget.exe restore KinectToVR.sln

    - name: NuGet Restore InputEmulator
      run: nuget.exe restore external/inputemulator/VRInputEmulator.sln

    - name: Build InputEmulator
      id: run_msbuild_ovrie
      run: |
        cd external/inputemulator/
        msbuild "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0" "/t:lib_vrinputemulator"
        
    - name: Build KinectToVR
      id: run_msbuild_k2vr
      run: msbuild "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"

    - name: Get short commit SHA
      id: slug
      run: "$slug = '::set-output name=slug::' + $env:GITHUB_SHA.SubString(0,7); echo $slug"

    - name: Upload KV2 Close Handler artifact
      uses: actions/upload-artifact@v2
      with:
        name: KV2CrashHandler-${{ steps.slug.outputs.slug }}.exe
        path: x64/Release/KV2CrashHandler.exe
        if-no-files-found: error

    - name: Upload KV1 Close Handler artifact
      uses: actions/upload-artifact@v2
      with:
        name: KV1CrashHandler-${{ steps.slug.outputs.slug }}.exe
        path: x64/Release/KV1CrashHandler.exe
        if-no-files-found: error

    - name: Upload PSMS artifact
      uses: actions/upload-artifact@v2
      with:
        name: PSMSProcess-${{ steps.slug.outputs.slug }}.exe
        path: x64/Release/PSMSProcess.exe
        if-no-files-found: error

    - name: Upload KV2 artifact
      uses: actions/upload-artifact@v2
      with:
        name: KinectV2Process-${{ steps.slug.outputs.slug }}.exe
        path: x64/Release/KinectV2Process.exe
        if-no-files-found: error

    - name: Upload KV1 artifact
      uses: actions/upload-artifact@v2
      with:
        name: KinectV1Process-${{ steps.slug.outputs.slug }}.exe
        path: x64/Release/KinectV1Process.exe
        if-no-files-found: error

    - name: Upload driver artifact
      uses: actions/upload-artifact@v2
      with:
        name: driver_KinectToVR-${{ steps.slug.outputs.slug }}.dll
        path: x64/Release/driver_KinectToVR.dll
        if-no-files-found: error
