name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      id: checkout_code

    - name: Setup MSBuild and add to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild
      
    - name: Install Wget
      run: choco install wget --no-progress

    - name: Setup Dependiences
      run: |
        git clone https://github.com/USCiLab/cereal external/cereal
        git clone https://github.com/ValveSoftware/openvr external/openvr
        wget "https://www.dropbox.com/s/9qledlbsehcywri/boost_1_74_0.7z?dl=1" -O ./external/boost_1_74_0.7z
        wget "https://drive.google.com/uc?export=download&id=14TBSyxF9AfTd5n05guthFRfpxeh0nxLX" -O ./external/kinectlib.7z
        7z x ./external/boost_1_74_0.7z -oexternal
        7z x ./external/kinectlib.7z -oexternal
        
    - name: Run MSBuild
      id: run_msbuild
      run: |
        dir
        msbuild "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"
