name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      id: checkout_code

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild
      
    - name: Install Wget
      run: choco install wget --no-progress

    - name: Setup Dependiences (Repos)
      run: |
        git clone https://github.com/USCiLab/cereal external/cereal
        git clone https://github.com/ValveSoftware/openvr external/openvr

    - name: Setup Dependiences (Custom)
      run: |
        wget -q "https://www.dropbox.com/s/9qledlbsehcywri/boost_1_74_0.7z?dl=1" -O ./external/boost_1_74_0.7z
        wget -q "https://drive.google.com/uc?export=download&id=14TBSyxF9AfTd5n05guthFRfpxeh0nxLX" -O ./external/kinectlib.7z
        7z x ./external/boost_1_74_0.7z -oexternal
        7z x ./external/kinectlib.7z -oexternal
        
    - name: Run MSBuild
      id: run_msbuild
      run: msbuild "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"

    - name: Get short commit SHA
      id: slug
      run: "$slug = '::set-output name=slug::' + $env:GITHUB_SHA.SubString(0,7); echo $slug"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: | 
          driver_KinectToVR-${{ steps.slug.outputs.slug }}.dll
          KinectV1Process-${{ steps.slug.outputs.slug }}.exe
          KinectV2Process-${{ steps.slug.outputs.slug }}.exe
          PSMSProcess-${{ steps.slug.outputs.slug }}.exe
        path: |
          x64/Release/driver_KinectToVR.exe
          x64/Release/KinectV1Process.exe
          x64/Release/KinectV2Process.exe
          x64/Release/PSMSProcess.exe
        if-no-files-found: error
